export enum UserRole {
  CUSTOMER = "CUSTOMER",
  PROFESSIONAL = "PROFESSIONAL",
  ADMIN = "ADMIN",
}

export enum ProfessionalType {
  INDEPENDENT = "INDEPENDENT",
  GARAGE = "GARAGE",
  BREAKDOWN_PROVIDER = "BREAKDOWN_PROVIDER",
  SPECIALIST = "SPECIALIST",
}

export enum InterventionStatus {
  REQUESTED = "REQUESTED",
  SEARCHING = "SEARCHING",
  OFFERED = "OFFERED",
  ACCEPTED = "ACCEPTED",
  EN_ROUTE = "EN_ROUTE",
  ARRIVED = "ARRIVED",
  DIAGNOSING = "DIAGNOSING",
  QUOTE_PENDING = "QUOTE_PENDING",
  QUOTE_ACCEPTED = "QUOTE_ACCEPTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID = "PAID",
  RATED = "RATED",
  CANCELLED = "CANCELLED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  NO_SHOW = "NO_SHOW",
  DISPUTED = "DISPUTED",
  FAILED = "FAILED",
}

export enum InterventionOfferStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum AvailabilityStatus {
  AVAILABLE_NOW = "AVAILABLE_NOW",
  AVAILABLE_SOON = "AVAILABLE_SOON",
  AVAILABLE_TODAY = "AVAILABLE_TODAY",
  APPOINTMENT = "APPOINTMENT",
  UNAVAILABLE = "UNAVAILABLE",
}

export enum VerificationStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum VerificationDocumentStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum QuoteStatus {
  DRAFT = "DRAFT",
  SENT = "SENT",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
}

export enum MessageType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  FILE = "FILE",
  SYSTEM = "SYSTEM",
}

export enum NotificationType {
  INTERVENTION = "INTERVENTION",
  MESSAGE = "MESSAGE",
  PAYMENT = "PAYMENT",
  QUOTE = "QUOTE",
  SYSTEM = "SYSTEM",
}
